### ISSUE TITLE
code 128 while installing 

### ISSUE THREAD

**Issue by Niwreg** [sebbo2002/atv2mqtt#2]
When trying to install i'll get the following:

sudo npm install -g @sebbo2002/atv2mqtt --unsafe-perm
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/sebbo2002/node-appletv.git /root/.npm/_cacache/tmp/git-clone-d0238abc
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d0238abc': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-17T07_58_39_615Z-debug.log

I'm running node -v
v9.9.0

and  npm -v
5.6.0

Because i'm trying this to run on an raspberry pi 2 with arm61. Any ideas? Or should i compile node from source?

**Comment by sebbo2002** [comment]
If you really need to use root for that, you can try this one:
```bash
sudo npm_config_user=root npm install -g @sebbo2002/atv2mqtt --unsafe-perm
```

**Comment by sebbo2002** [comment]
Due to inactivity I would close this issue here.
